version = "Two"
unstable_features = true

error_on_line_overflow = true
error_on_unformatted = true

max_width = 80
doc_comment_code_block_width = 80
enum_discrim_align_threshold = 20
struct_field_align_threshold = 20

format_strings = true
format_macro_matchers = true
wrap_comments = true
normalize_comments = true
format_code_in_doc_comments = true
normalize_doc_attributes = true
hex_literal_case = "Upper"
newline_style = "Unix"

imports_layout = "HorizontalVertical"
imports_granularity = "Crate"
group_imports = "StdExternalCrate"

combine_control_expr = false
condense_wildcard_suffixes = true
match_block_trailing_comma = true
reorder_impl_items = true
use_field_init_shorthand = true
use_try_shorthand = true
